development: &development
  bucket: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

test:
  <<: *development

production:
  bucket: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>