# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e72d381e7d8491b9880551753c94d80943a605c0ff972bb2d29dd377226b8b89b6f2200c03c06eb706a8915eb0a613d8901453df96f72f9607f9a10aae9f1511

test:
  secret_key_base: 3dc5666e4196e25b81e2e233272e4433cfb139e614ebce7a37db4207b58a9d5ef4697263fca2c4d4b017961994e70648cb920f65b62182cb6aac8231c221fca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
